### PR TITLE
Fix #191. Fix #192. Fix some of the left over type issues

### LINKED ISSUE #191: Add -Wconversion to the clang builds too

### LINKED ISSUE #192: Fix some minor type issues on clang/macos.

### PR DESCRIPTION
**Pull request by omalley**
This fix does:
* applies -Wconversion to both clang and gcc on all parts of the project
* enforces the -Werror again
* fixes some warnings that had snuck in
* adds a cmake test for whether int64_t is long or long long so that we can use the right type on each platform
* adds a "-p" for mkdir so that we don't complain when the java directory exists
* added the license to FileMetadata.cc

### CODE REVIEW

File: orc-c++/src/orc/ColumnPrinter.cc [hunk 1]
```diff
@@ -290,7 +291,7 @@ namespace orc {
       writeString(buffer, "null");
     } else {
       char numBuffer[64];
-      snprintf(numBuffer, sizeof(numBuffer), "%ld",
+      snprintf(numBuffer, sizeof(numBuffer), "%" INT64_FORMAT_STRING "d",
```
Comment (asandryh) [inline orc-c++/src/orc/ColumnPrinter.cc]: That's a nice trick!

**Comment by omalley** [comment]
Aliaksei, 
  Can you +1 the patch. I'd like to get this committed.

**Comment by asandryh** [comment]
+1.
